[package]
name = "subx"
version = "0.1.0"
edition = "2021"
authors = ["Your Name <your.email@example.com>"]
description = "智慧字幕處理 CLI 工具"
license = "GPLv3"
repository = "https://github.com/yourusername/subx"
keywords = ["subtitle", "cli", "ai", "video"]
categories = ["command-line-utilities", "multimedia"]

[dependencies]
# CLI 框架
clap = { version = "4.4", features = ["derive", "cargo"] }
clap_complete = "4.4"

# 字幕格式解析相依
regex = "1.0"
encoding_rs = "0.8"

# 非同步執行時
tokio = { version = "1.0", features = ["full"] }

# 錯誤處理
anyhow = "1.0"
thiserror = "1.0"

# 序列化
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.8"

# HTTP 客戶端
reqwest = { version = "0.11", features = ["json", "rustls-tls"] }

# 檔案掃描
walkdir = "2.3"

# 並行處理支援
futures = "0.3"

# 非同步 trait 支援
async-trait = "0.1"

# 日誌
log = "0.4"
env_logger = "0.10"

# 用戶介面
colored = "2.0"
indicatif = "0.17"
dialoguer = "0.10"
md5 = "0.7"

# 配置管理相依：路徑解析與多核心檢測
# 音訊處理
symphonia = { version = "0.5", features = ["all"] }

# 配置管理相依：路徑解析與多核心檢測
dirs = "4.0"
num_cpus = "1.0"

[dev-dependencies]
tokio-test = "0.4"
assert_cmd = "2.0"
predicates = "3.0"
tempfile = "3.8"

[[bin]]
name = "subx"
path = "src/main.rs"
