# .config/nextest.toml
#
# Configuration for cargo nextest
# https://nexte.st/book/configuration.html

[profile.default]
# 設定測試超時時間 (60 秒)
slow-timeout = { period = "120s", terminate-after = 1 }

# 設定最大並行測試數量，使用 CPU 核心數
test-threads = "num-cpus"

# 設定重試次數
retries = 1

# 測試失敗時的行為
failure-output = "immediate"

# 設定測試狀態級別
status-level = "pass"

# 設定測試輸出格式
final-status-level = "slow"

[profile.ci]
# CI 環境的設定
retries = 2
slow-timeout = { period = "240s", terminate-after = 2 }
test-threads = 4
failure-output = "final"
status-level = "fail"

[profile.quick]
# 快速測試設定
retries = 0
slow-timeout = { period = "30s", terminate-after = 1 }
test-threads = "num-cpus"
failure-output = "immediate"

[profile.default.junit]
# JUnit XML 輸出設定
path = "target/nextest/junit.xml"
